# Generated by Django 4.2.16 on 2026-09-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('type', models.CharField(choices=[('review', '审核通知'), ('order', '订单通知'), ('favorite', '收藏通知'), ('system', '系统通知')], default='system', max_length=20, verbose_name='类型')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
