# Generated by Django 4.2.16 on 2026-09-14 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bought_orders', to=settings.AUTH_USER_MODEL, verbose_name='买家'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_orders', to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='idx_order_buyer_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', '-created_at'], name='idx_order_seller_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', 'status'], name='idx_order_product_status'),
        ),
    ]
